# Generated by Django 4.2.20 on 2025-05-22 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarouselImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Título')),
                ('subtitle', models.CharField(blank=True, max_length=200, verbose_name='Subtítulo')),
                ('image', models.ImageField(upload_to='carousel/', verbose_name='Imagen')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Orden')),
                ('active', models.BooleanField(default=True, verbose_name='Activo')),
                ('button_text', models.CharField(blank=True, max_length=50, verbose_name='Texto del botón')),
                ('button_url', models.CharField(blank=True, max_length=200, verbose_name='URL del botón')),
            ],
            options={
                'verbose_name': 'Imagen del carrusel',
                'verbose_name_plural': 'Imágenes del carrusel',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SiteImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(choices=[('home_about', 'Imagen Sección Nosotros (Home)'), ('about_banner', 'Banner página Nosotros'), ('contact_banner', 'Banner página Contacto'), ('about_team1', 'Miembro del equipo 1'), ('about_team2', 'Miembro del equipo 2'), ('about_team3', 'Miembro del equipo 3')], max_length=50, unique=True, verbose_name='Ubicación')),
                ('title', models.CharField(blank=True, max_length=100, verbose_name='Título/Nombre')),
                ('description', models.TextField(blank=True, verbose_name='Cargo/Descripción breve')),
                ('bio', models.TextField(blank=True, verbose_name='Biografía detallada')),
                ('linkedin_url', models.URLField(blank=True, verbose_name='URL de LinkedIn')),
                ('instagram_url', models.URLField(blank=True, verbose_name='URL de Instagram')),
                ('image', models.ImageField(upload_to='site_images/', verbose_name='Imagen')),
            ],
            options={
                'verbose_name': 'Imagen del sitio',
                'verbose_name_plural': 'Imágenes del sitio',
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Decoraciones Mori', max_length=100, verbose_name='Nombre del sitio')),
                ('logo', models.ImageField(upload_to='site_settings/', verbose_name='Logo')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='site_settings/', verbose_name='Favicon')),
                ('footer_text', models.TextField(blank=True, verbose_name='Texto del pie de página')),
                ('facebook_url', models.URLField(blank=True, verbose_name='URL de Facebook')),
                ('instagram_url', models.URLField(blank=True, verbose_name='URL de Instagram')),
                ('whatsapp_number', models.CharField(blank=True, max_length=20, verbose_name='Número de WhatsApp')),
                ('address', models.TextField(blank=True, verbose_name='Dirección')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
            ],
            options={
                'verbose_name': 'Configuración del sitio',
                'verbose_name_plural': 'Configuración del sitio',
            },
        ),
    ]
