# Generated by Django 5.2 on 2025-05-11 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_config', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteimage',
            name='location',
            field=models.CharField(choices=[('home_about', 'Imagen Sección Nosotros (Home)'), ('home_services', 'Imagen Sección Servicios (Home)'), ('home_testimonial1', 'Testimonio 1'), ('home_testimonial2', 'Testimonio 2'), ('home_testimonial3', 'Testimonio 3'), ('about_banner', 'Banner página Nosotros'), ('contact_banner', 'Banner página Contacto'), ('services_banner', 'Banner página Servicios'), ('about_team1', 'Miembro del equipo 1'), ('about_team2', 'Miembro del equipo 2'), ('about_team3', 'Miembro del equipo 3')], max_length=50, unique=True, verbose_name='Ubicación'),
        ),
    ]
