# Generated by Django 5.2 on 2025-05-11 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_config', '0002_alter_siteimage_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteimage',
            name='bio',
            field=models.TextField(blank=True, verbose_name='Biografía detallada'),
        ),
        migrations.AddField(
            model_name='siteimage',
            name='instagram_url',
            field=models.URLField(blank=True, verbose_name='URL de Instagram'),
        ),
        migrations.AddField(
            model_name='siteimage',
            name='linkedin_url',
            field=models.URLField(blank=True, verbose_name='URL de LinkedIn'),
        ),
        migrations.AlterField(
            model_name='siteimage',
            name='description',
            field=models.TextField(blank=True, verbose_name='Cargo/Descripción breve'),
        ),
        migrations.AlterField(
            model_name='siteimage',
            name='title',
            field=models.CharField(blank=True, max_length=100, verbose_name='Título/Nombre'),
        ),
    ]
