# Generated by Django 4.2.20 on 2025-05-11 22:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0010_scheduledworkday_workscheduletemplate_and_more'),
        ('invoices', '0002_invoice_advance_payment_invoice_appointment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceitem',
            name='advance_payment',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Adelanto recibido'),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='appointment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_invoice_items', to='appointments.appointment', verbose_name='Cita relacionada'),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='pending_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Saldo pendiente'),
        ),
    ]
