# Generated by Django 4.2.20 on 2025-05-22 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0003_invoiceitem_advance_payment_invoiceitem_appointment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='inventory_processed',
            field=models.BooleanField(default=False, help_text='Indica si los productos de esta boleta ya afectaron el inventario', verbose_name='Inventario procesado'),
        ),
    ]
