# Generated by Django 5.1.6 on 2025-12-02 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0004_invoice_inventory_processed'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoice',
            options={'ordering': ['-date_issued', '-number'], 'verbose_name': 'Boleta de Venta', 'verbose_name_plural': 'Facturación'},
        ),
    ]
