# Generated by Django 5.0.4 on 2025-04-10 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_service_slug_alter_serviceimage_image_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='product',
            table='producto',
        ),
        migrations.AlterModelTable(
            name='service',
            table='servicio',
        ),
        migrations.AlterModelTable(
            name='servicecategory',
            table='categoria_servicio',
        ),
        migrations.AlterModelTable(
            name='serviceimage',
            table='imagen_servicio',
        ),
        migrations.AlterModelTable(
            name='servicevideo',
            table='video_servicio',
        ),
    ]
