# Generated by Django 5.0.4 on 2025-05-02 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_alter_product_table_alter_service_table_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceimage',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servicevideo',
            name='video_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
