# Generated by Django 5.0.4 on 2025-05-02 22:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_serviceimage_image_url_servicevideo_video_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='serviceimage',
            options={'verbose_name': 'Imagen del servicio', 'verbose_name_plural': 'Imágenes del servicio'},
        ),
        migrations.AlterModelOptions(
            name='servicevideo',
            options={'verbose_name': 'Video del servicio', 'verbose_name_plural': 'Videos del servicio'},
        ),
        migrations.AlterField(
            model_name='serviceimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='services/', verbose_name='Imagen (archivo)'),
        ),
        migrations.AlterField(
            model_name='serviceimage',
            name='image_url',
            field=models.URLField(blank=True, null=True, verbose_name='Imagen (URL)'),
        ),
        migrations.AlterField(
            model_name='serviceimage',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='Destacada'),
        ),
        migrations.AlterField(
            model_name='serviceimage',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='services.service', verbose_name='Servicio'),
        ),
        migrations.AlterField(
            model_name='servicevideo',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='services.service', verbose_name='Servicio'),
        ),
        migrations.AlterField(
            model_name='servicevideo',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='servicevideo',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='service_videos/', verbose_name='Video (archivo)'),
        ),
        migrations.AlterField(
            model_name='servicevideo',
            name='video_url',
            field=models.URLField(blank=True, null=True, verbose_name='Video (URL)'),
        ),
        migrations.AlterModelTable(
            name='serviceimage',
            table=None,
        ),
        migrations.AlterModelTable(
            name='servicevideo',
            table=None,
        ),
    ]
