# Generated by Django 5.0.4 on 2025-05-03 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_alter_serviceimage_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicevideo',
            name='video_url',
            field=models.TextField(blank=True, null=True, verbose_name='Código de incorporación <iframe>'),
        ),
    ]
