# Generated by Django 5.0.4 on 2025-05-03 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_alter_servicevideo_video_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceimage',
            name='image_url',
            field=models.TextField(blank=True, null=True, verbose_name='Código de incorporación <iframe>'),
        ),
    ]
