# Generated by Django 5.0.4 on 2025-05-05 09:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_alter_serviceimage_image_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='serviceimage',
            options={'verbose_name': 'Service Image', 'verbose_name_plural': 'Service Images'},
        ),
        migrations.AlterModelOptions(
            name='servicevideo',
            options={'verbose_name': 'Service Video', 'verbose_name_plural': 'Service Videos'},
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, db_column='categoria_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='services.servicecategory', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(db_column='descripcion', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(db_column='esta_activo', default=True, verbose_name='Is active'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(db_column='nombre', max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_per_unit',
            field=models.DecimalField(db_column='precio_por_unidad', decimal_places=2, max_digits=10, verbose_name='Price per unit'),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(db_column='unidad', help_text='e.g., square meter, piece', max_length=20, verbose_name='Unit'),
        ),
        migrations.AlterField(
            model_name='service',
            name='base_price',
            field=models.DecimalField(db_column='precio_base', decimal_places=2, max_digits=10, verbose_name='Base Price'),
        ),
        migrations.AlterField(
            model_name='service',
            name='category',
            field=models.ForeignKey(db_column='categoria_id', on_delete=django.db.models.deletion.CASCADE, related_name='services', to='services.servicecategory', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='service',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_column='fecha_creacion', verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.TextField(db_column='descripcion', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='service',
            name='is_active',
            field=models.BooleanField(db_column='esta_activo', default=True, verbose_name='Is active'),
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(db_column='nombre', max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='service',
            name='slug',
            field=models.SlugField(blank=True, db_column='slug', max_length=100, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='service',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_column='fecha_actualizacion', verbose_name='Updated at'),
        ),
        migrations.AlterField(
            model_name='servicecategory',
            name='description',
            field=models.TextField(blank=True, db_column='descripcion', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='servicecategory',
            name='name',
            field=models.CharField(db_column='nombre', max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='serviceimage',
            name='image',
            field=models.ImageField(blank=True, db_column='imagen_archivo', null=True, upload_to='services/', verbose_name='Imagen (archivo)'),
        ),
        migrations.AlterField(
            model_name='serviceimage',
            name='image_url',
            field=models.TextField(blank=True, db_column='imagen_url_embebida', null=True, verbose_name='Código de incorporación <iframe>'),
        ),
        migrations.AlterField(
            model_name='serviceimage',
            name='is_featured',
            field=models.BooleanField(db_column='es_destacada', default=False, verbose_name='Destacada'),
        ),
        migrations.AlterField(
            model_name='serviceimage',
            name='service',
            field=models.ForeignKey(db_column='servicio_id', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='services.service', verbose_name='Servicio'),
        ),
        migrations.AlterField(
            model_name='servicevideo',
            name='service',
            field=models.ForeignKey(db_column='servicio_id', on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='services.service', verbose_name='Servicio'),
        ),
        migrations.AlterField(
            model_name='servicevideo',
            name='title',
            field=models.CharField(db_column='titulo', max_length=200, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='servicevideo',
            name='video',
            field=models.FileField(blank=True, db_column='video_archivo', null=True, upload_to='service_videos/', verbose_name='Video (archivo)'),
        ),
        migrations.AlterField(
            model_name='servicevideo',
            name='video_url',
            field=models.TextField(blank=True, db_column='video_url_embebido', null=True, verbose_name='Código de incorporación <iframe>'),
        ),
    ]
