# Generated by Django 5.0.4 on 2025-05-05 09:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_alter_serviceimage_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='serviceimage',
            options={'verbose_name': 'Imagen del servicio', 'verbose_name_plural': 'Imágenes del servicio'},
        ),
        migrations.AlterModelOptions(
            name='servicevideo',
            options={'verbose_name': 'Video del servicio', 'verbose_name_plural': 'Videos del servicio'},
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='services.servicecategory'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is active'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_per_unit',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price per unit'),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(help_text='e.g., square meter, piece', max_length=20, verbose_name='Unit'),
        ),
        migrations.AlterField(
            model_name='service',
            name='base_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Base Price'),
        ),
        migrations.AlterField(
            model_name='service',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='services.servicecategory'),
        ),
        migrations.AlterField(
            model_name='service',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='service',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is active'),
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='service',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='service',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='servicecategory',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='servicecategory',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='serviceimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='services/', verbose_name='Imagen (archivo)'),
        ),
        migrations.AlterField(
            model_name='serviceimage',
            name='image_url',
            field=models.TextField(blank=True, null=True, verbose_name='Código de incorporación <iframe>'),
        ),
        migrations.AlterField(
            model_name='serviceimage',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='Destacada'),
        ),
        migrations.AlterField(
            model_name='serviceimage',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='services.service', verbose_name='Servicio'),
        ),
        migrations.AlterField(
            model_name='servicevideo',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='services.service', verbose_name='Servicio'),
        ),
        migrations.AlterField(
            model_name='servicevideo',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='servicevideo',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='service_videos/', verbose_name='Video (archivo)'),
        ),
        migrations.AlterField(
            model_name='servicevideo',
            name='video_url',
            field=models.TextField(blank=True, null=True, verbose_name='Código de incorporación <iframe>'),
        ),
    ]
