# Generated by Django 4.2.20 on 2025-05-14 04:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0009_alter_serviceimage_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='Cantidad')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.product')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='services.service')),
            ],
            options={
                'verbose_name': 'Componente de Servicio',
                'verbose_name_plural': 'Componentes de Servicio',
                'db_table': 'componente_servicio',
                'unique_together': {('service', 'product')},
            },
        ),
    ]
