# Generated by Django 4.2.20 on 2025-05-14 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0010_servicecomponent'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Stock'),
        ),
        migrations.AddField(
            model_name='product',
            name='stock_min',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Stock mínimo'),
        ),
    ]
