# Generated by Django 4.2.20 on 2025-05-18 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0013_alter_product_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, default='sin-nombre', max_length=100, unique=True, verbose_name='Slug'),
            preserve_default=False,
        ),
    ]
