# Generated by Django 5.0.4 on 2025-05-07 03:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_type', models.CharField(choices=[('prospect', 'Prospecto'), ('active', 'Activo'), ('inactive', 'Inactivo')], default='prospect', help_text='Clasificación del cliente (ej. prospecto, activo, inactivo)', max_length=20, verbose_name='Tipo de cliente')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='client_profile', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Perfil de Cliente',
                'verbose_name_plural': 'Perfiles de Cliente',
                'db_table': 'cliente_perfil',
            },
        ),
    ]
