# Generated by Django 5.0.4 on 2025-05-07 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
    ]
