# Generated by Django 5.0.4 on 2025-05-07 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_create_existing_client_profiles'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientprofile',
            options={'verbose_name': 'Cliente', 'verbose_name_plural': 'Clientes'},
        ),
        migrations.AlterField(
            model_name='clientprofile',
            name='client_type',
            field=models.CharField(choices=[('prospect', 'Prospecto'), ('active', 'Activo'), ('inactive', 'Inactivo')], default='prospect', max_length=20, verbose_name='Tipo de cliente'),
        ),
        migrations.AlterModelTable(
            name='clientprofile',
            table=None,
        ),
    ]
