# Generated by Django 5.0.4 on 2025-04-11 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='usuario',
        ),
    ]
