# Generated by Django 4.2.20 on 2025-05-21 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='code_expiry',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Code expiry'),
        ),
        migrations.AddField(
            model_name='user',
            name='verification_code',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Verification code'),
        ),
    ]
