# Generated by Django 5.1.6 on 2025-12-02 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_code_expiry_user_verification_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ruc',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='RUC'),
        ),
    ]
