# Generated by Django 4.2.20 on 2025-05-22 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0014_alter_product_slug'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorymovement',
            name='draft',
            field=models.BooleanField(default=False, help_text='Indica si este movimiento está en borrador y no debe afectar al inventario real', verbose_name='Borrador'),
        ),
        migrations.AlterModelTable(
            name='inventorymovement',
            table='movimiento_inventario',
        ),
        migrations.CreateModel(
            name='InventoryStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_stock', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Stock Actual')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_status', to='services.product')),
            ],
            options={
                'verbose_name': 'Estado de Inventario',
                'verbose_name_plural': 'Estados de Inventario',
                'db_table': 'estado_inventario',
            },
        ),
    ]
