# Generated by Django 4.2.20 on 2025-05-22 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_inventorymovement_draft_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='inventorymovement',
            table=None,
        ),
        migrations.AlterModelTable(
            name='inventorystatus',
            table=None,
        ),
    ]
