"""
Django settings for DecoracionesMori project.

Generated by 'django-admin startproject' using Django 5.1.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-@5^lch0ee2hwx7fa8w%^67u*@ce1i%ci@+y@8x#wo&ar6_qs+0'


# In settings.py
MAPS_API_KEY = os.environ.get('MAPS_API_KEY', '')  # Get from environment or use empty string

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
    'localhost',
    'decoracionesmori.onrender.com',
    '127.0.0.1',
]

STATICFILES_FINDERS = [
         'django.contrib.staticfiles.finders.FileSystemFinder',
         'django.contrib.staticfiles.finders.AppDirectoriesFinder',
     ]
    

# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'accounts',
    'services',  # Ensure this line is present
    'appointments', 
    'invoices',
    'site_config',
    'inventory',

    #plottly dash
    'django_plotly_dash.apps.DjangoPlotlyDashConfig',
    'channels',


    #google auth
    'clients.apps.ClientsConfig', # O la ruta a tu AppConfig

    # Allauth
    'django.contrib.sites',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',


]

# Add these settings for django-plotly-dash
X_FRAME_OPTIONS = 'SAMEORIGIN'
PLOTLY_DASH = {
    "mapping_function": None,
    "access_without_dash": False,
}

CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels.layers.InMemoryChannelLayer'
    }
}

AUTH_USER_MODEL = 'accounts.User'


AUTHENTICATION_BACKENDS = [
    # Django's default authentication backend
    'django.contrib.auth.backends.ModelBackend',
    
    # Add the django-allauth authentication backend
    'allauth.account.auth_backends.AuthenticationBackend',
]

# Configuraciones de django-allauth
SITE_ID = 1  # Asegúrate de tener un Site configurado en el admin

# Quita estas configuraciones antiguas
ACCOUNT_AUTHENTICATION_METHOD = 'username_email'
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_USERNAME_REQUIRED = True



# Configuraciones de inicio de sesión social
SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'SCOPE': [
            'profile',
            'email',
        ],
        'AUTH_PARAMS': {
            'access_type': 'online',
        }
    }
}

# URLs de redireccionamiento
LOGIN_REDIRECT_URL = 'home'
LOGOUT_REDIRECT_URL = 'home'
ACCOUNT_LOGOUT_ON_GET = True  # Permite cerrar sesión con un simple GET

JAZZMIN_SETTINGS = {
    "custom_css": "css/custom_admin.css",
    "custom_js": "js/custom_admin.js",
    "site_title": "Decoraciones Mori",
    "site_header": "Decoraciones Mori Admin",
    "site_brand": "Decoraciones Mori",
    "welcome_sign": "Bienvenido al Panel de Administración",
    "site_logo": "imagen/logo.png",
    "site_icon": "imagen/logo.png", 
    
    "show_sidebar": True,
    "navigation_expanded": True,
    "search_model": ["auth.User", "services.Service", "services.Product"],
    "language_chooser": False,
    "changeform_format": "horizontal_tabs",
    "topmenu_links": [
        {"name": "Inicio", "url": "admin:index", "permissions": ["auth.view_user"]},
        {"name": "Sitio Web", "url": "/", "new_window": True},
        {"model": "auth.User"},
    ],
    "usermenu_links": [
        {"name": "Soporte", "url": "mailto:zuluetamori@gmail.com", "new_window": True},
        {"model": "auth.user"}
    ],
    "show_ui_builder": True,
    "icons": {
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",
        "auth.Group": "fas fa-users",
        "services.Service": "fas fa-couch",
        "services.Product": "fas fa-box",
        "services.ServiceCategory": "fas fa-tags",
        "services.ProductCategory": "fas fa-tags",
        "services.ServiceImage": "fas fa-image",
        "services.ServiceVideo": "fas fa-video",
        "appointments.Appointment": "fas fa-calendar-alt",
        "quotations.Quotation": "fas fa-file-invoice-dollar",
        "accounts.Profile": "fas fa-id-card",
    },
    "default_icon_parents": "fas fa-folder",
    "default_icon_children": "fas fa-circle",
    "related_modal_active": True,
    "hide_apps": [],
    "hide_models": [],
    "order_with_respect_to": [
        "auth", 
        "accounts", 
        "services", 
        "quotations", 
        "appointments"
    ],
   
    "menu": [
        {"app": "auth", "label": "Autenticación", "icon": "fas fa-users-cog"},
        {"app": "accounts", "label": "Cuentas", "icon": "fas fa-users"},
        {
            "label": "Servicios",
            "icon": "fas fa-couch",
            "models": [
                {"model": "services.Service", "label": "Servicios"},
                {"model": "services.ServiceCategory", "label": "Categorías de Servicios"},
                {"model": "services.ServiceImage", "label": "Imágenes de Servicios"},
                {"model": "services.ServiceVideo", "label": "Videos de Servicios"}
            ]
        },
        {
            "label": "Productos",
            "icon": "fas fa-box",
            "models": [
                {"model": "services.Product", "label": "Productos"},
                {"model": "services.ProductCategory", "label": "Categorías de Productos"}
            ]
        },
        {"app": "appointments", "label": "Citas", "icon": "fas fa-calendar-alt"},
        {"app": "quotations", "label": "Cotizaciones", "icon": "fas fa-file-invoice-dollar"},
        {
            "label": "Configuración del Sitio",
            "icon": "fas fa-cogs",
            "models": [
                {"model": "site_config.SiteSettings", "label": "Ajustes del Sitio"},
                {"model": "site_config.ContactInfo", "label": "Información de Contacto"},
                {"model": "site_config.SocialMediaLinks", "label": "Enlaces de Redes Sociales"},
            ]
            
        },
    ],
    

}

# Configuración adicional para traducir textos estáticos de Jazzmin
JAZZMIN_UI_TWEAKS = {
    "navbar_small_text": False,
    "footer_small_text": False,
    "body_small_text": False,
    "brand_small_text": False,
    "brand_colour": "navbar-dark",
    "accent": "accent-primary",
    "navbar": "navbar-dark",
    "no_navbar_border": False,
    "navbar_fixed": True,
    "layout_boxed": False,
    "footer_fixed": False,
    "sidebar_fixed": True,
    "sidebar": "sidebar-dark-primary",
    "sidebar_nav_small_text": False,
    "sidebar_disable_expand": False,
    "sidebar_nav_child_indent": True,
    "sidebar_nav_compact_style": False,
    "sidebar_nav_legacy_style": False,
    "sidebar_nav_flat_style": False,
    
    
    "button_classes": {
        "primary": "btn-primary",
        "secondary": "btn-secondary",
        "info": "btn-info",
        "warning": "btn-warning",
        "danger": "btn-danger",
        "success": "btn-success",
    },
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware', # <--- ¡IMPORTANTE!
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware',
    'django_plotly_dash.middleware.BaseMiddleware',


]

ROOT_URLCONF = 'DecoracionesMori.urls'


LOGIN_REDIRECT_URL = '/'  # Redirige a la página principal después de iniciar sesión

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'site_config.context_processors.site_settings',
            ],
        },
    },
]
#cofiguracion de estilos de logeo con gmail
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'loggers': {
        'django.template': {
            'handlers': ['console'],
            'level': 'DEBUG',
        },
        'allauth': {
            'handlers': ['console'],
            'level': 'DEBUG',
        },
    },
}

WSGI_APPLICATION = 'DecoracionesMori.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases
'''
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'decoraciones_mori',
        'USER': 'root',
        'PASSWORD': 'D1alZuM0',
        'HOST': '127.0.0.1',
        'PORT': '3306',
    }
}
'''
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'es'

TIME_ZONE = 'America/Lima'

USE_I18N = True

USE_L10N = True

USE_TZ = False

# --- Rutas para buscar archivos de traducción (.po, .mo) ---
# ¡Esta es la línea clave que necesitas añadir/asegurar!
LOCALE_PATHS = [
    BASE_DIR / 'locale',
    # os.path.join(BASE_DIR, 'locale'), # Alternativa si usas os.path
]

# Opcional: Lista de idiomas disponibles
# from django.utils.translation import gettext_lazy as _
# LANGUAGES = [
#    ('en', _('English')),
#    ('es', _('Spanish')),
# ]


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'
MEDIA_URL = '/media/'





# Asegúrate de que esta ruta sea correcta para tu proyecto.
# Por ejemplo, si tienes una carpeta 'static' en la raíz de tu proyecto:
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]
# Ruta absoluta en el sistema de archivos donde se guardarán los archivos subidos
# Asegúrate de que esta carpeta exista y tenga permisos de escritura para el servidor web
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
STATICFILES_DIRS = [
    BASE_DIR / "static",
]

STATIC_ROOT = BASE_DIR / "staticfiles"

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'  # Or your preferred email provider
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER') # <-- Lee el usuario del .env
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD') # <-- Lee la contraseña del .env
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER # <-- IMPORTANTE: Establece el remitente por defecto
# Leer la NUEVA clave desde la variable de entorno
