"""
Django settings for DecoracionesMori project.

Generated by 'django-admin startproject' using Django 5.1.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-@5^lch0ee2hwx7fa8w%^67u*@ce1i%ci@+y@8x#wo&ar6_qs+0'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'accounts',
    'services',  # Ensure this line is present
    'quotations',
    'appointments',   


]
    
JAZZMIN_SETTINGS = {
    "site_title": "Decoraciones Mori",
    "site_header": "Decoraciones Mori Admin",
    "site_brand": "Decoraciones Mori",
    "welcome_sign": "Bienvenido al Panel de Administración",
    "site_logo": "imagen/logo.png",
    "theme": "darkly",
    "show_sidebar": True,
    "navigation_expanded": True,
    "search_model": ["auth.User", "services.Service", "services.Product"],
    "language_chooser": False,
    "custom_css": "css/custom_admin.css",
    "custom_js": "js/custom_admin.js",
    "changeform_format": "horizontal_tabs",
    "topmenu_links": [
        {"name": "Inicio", "url": "admin:index", "permissions": ["auth.view_user"]},
        {"name": "Sitio Web", "url": "/", "new_window": True},
        {"model": "auth.User"},
    ],
    "usermenu_links": [
        {"name": "Soporte", "url": "mailto:zuluetamori@gmail.com", "new_window": True},
        {"model": "auth.user"}
    ],
    "show_ui_builder": True,
    "icons": {
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",
        "auth.Group": "fas fa-users",
        "services.Service": "fas fa-couch",
        "services.Product": "fas fa-box",
        "services.ServiceCategory": "fas fa-tags",
        "services.ProductCategory": "fas fa-tags",
        "services.ServiceImage": "fas fa-image",
        "services.ServiceVideo": "fas fa-video",
        "appointments.Appointment": "fas fa-calendar-alt",
        "quotations.Quotation": "fas fa-file-invoice-dollar",
        "accounts.Profile": "fas fa-id-card",
    },
    "default_icon_parents": "fas fa-folder",
    "default_icon_children": "fas fa-circle",
    "related_modal_active": True,
    "hide_apps": [],
    "hide_models": [],
    "order_with_respect_to": [
        "auth", 
        "accounts", 
        "services", 
        "quotations", 
        "appointments"
    ],
    "custom_links": {
        "services": [{
            "name": "Reporte de Servicios", 
            "url": "admin:service_report", 
            "icon": "fas fa-chart-bar"
        }],
        "quotations": [{
            "name": "Exportar Cotizaciones", 
            "url": "admin:export_quotations", 
            "icon": "fas fa-file-export"
        }]
    },
    "menu": [
        {"app": "auth", "label": "Autenticación", "icon": "fas fa-users-cog"},
        {"app": "accounts", "label": "Cuentas", "icon": "fas fa-users"},
        {
            "label": "Servicios",
            "icon": "fas fa-couch",
            "models": [
                {"model": "services.Service", "label": "Servicios"},
                {"model": "services.ServiceCategory", "label": "Categorías de Servicios"},
                {"model": "services.ServiceImage", "label": "Imágenes de Servicios"},
                {"model": "services.ServiceVideo", "label": "Videos de Servicios"}
            ]
        },
        {
            "label": "Productos",
            "icon": "fas fa-box",
            "models": [
                {"model": "services.Product", "label": "Productos"},
                {"model": "services.ProductCategory", "label": "Categorías de Productos"}
            ]
        },
        {"app": "appointments", "label": "Citas", "icon": "fas fa-calendar-alt"},
        {"app": "quotations", "label": "Cotizaciones", "icon": "fas fa-file-invoice-dollar"},
        {
            "label": "Reportes",
            "icon": "fas fa-chart-line",
            "models": [
                {"url": "admin:service_report", "label": "Reporte de Servicios"},
                {"url": "admin:quotation_report", "label": "Reporte de Cotizaciones"},
                {"url": "admin:appointment_report", "label": "Reporte de Citas"}
            ]
        },
    ],
    #login panel admin
    

}

# Configuración adicional para traducir textos estáticos de Jazzmin
JAZZMIN_UI_TWEAKS = {
    "navbar_small_text": False,
    "footer_small_text": False,
    "body_small_text": False,
    "brand_small_text": False,
    "brand_colour": "navbar-dark",
    "accent": "accent-primary",
    "navbar": "navbar-dark",
    "no_navbar_border": False,
    "navbar_fixed": True,
    "layout_boxed": False,
    "footer_fixed": False,
    "sidebar_fixed": True,
    "sidebar": "sidebar-dark-primary",
    "sidebar_nav_small_text": False,
    "sidebar_disable_expand": False,
    "sidebar_nav_child_indent": True,
    "sidebar_nav_compact_style": False,
    "sidebar_nav_legacy_style": False,
    "sidebar_nav_flat_style": False,
    "theme": "darkly",
    "dark_mode_theme": "darkly",
    "button_classes": {
        "primary": "btn-primary",
        "secondary": "btn-secondary",
        "info": "btn-info",
        "warning": "btn-warning",
        "danger": "btn-danger",
        "success": "btn-success",
    },
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'DecoracionesMori.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'DecoracionesMori.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'decoraciones_mori',
        'USER': 'root',
        'PASSWORD': 'D1alZuM0',
        'HOST': '127.0.0.1',
        'PORT': '3306',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'es'

TIME_ZONE = 'America/Lima'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
STATICFILES_DIRS = [
    BASE_DIR / "static",
]

STATIC_ROOT = BASE_DIR / "staticfiles"

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'  # Or your preferred email provider
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = ''