# Generated by Django 5.0.4 on 2025-03-31 05:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_alter_appointment_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staffavailability',
            options={'ordering': ['date', 'start_time'], 'verbose_name': 'Disponibilidad', 'verbose_name_plural': 'Disponibilidades'},
        ),
        migrations.AlterField(
            model_name='staffavailability',
            name='end_time',
            field=models.TimeField(default=datetime.time(17, 0)),
        ),
        migrations.AlterField(
            model_name='staffavailability',
            name='start_time',
            field=models.TimeField(default=datetime.time(9, 0)),
        ),
    ]
