# Generated by Django 5.0.4 on 2025-03-31 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_alter_staffavailability_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='staffavailability',
            unique_together=set(),
        ),
    ]
