# Generated by Django 5.0.4 on 2025-04-02 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('appointments', '0005_alter_appointment_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'verbose_name': 'Appointment', 'verbose_name_plural': 'Appointments'},
        ),
        migrations.AlterModelOptions(
            name='staffavailability',
            options={'verbose_name': 'Staff Availability', 'verbose_name_plural': 'Staff Availabilities'},
        ),
        migrations.AlterField(
            model_name='appointment',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='staffavailability',
            name='end_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='staffavailability',
            name='start_time',
            field=models.TimeField(),
        ),
        migrations.AlterUniqueTogether(
            name='staffavailability',
            unique_together={('staff', 'date', 'start_time')},
        ),
    ]
