# Generated by Django 5.0.4 on 2025-04-05 23:34

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('appointments', '0006_alter_appointment_options_and_more'),
        ('services', '0002_service_slug_alter_serviceimage_image_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'ordering': ['-created_at'], 'verbose_name': 'Cita', 'verbose_name_plural': 'Citas'},
        ),
        migrations.AlterModelOptions(
            name='staffavailability',
            options={'verbose_name': 'Disponibilidad de Personal', 'verbose_name_plural': 'Disponibilidades de Personal'},
        ),
        migrations.AddField(
            model_name='appointment',
            name='client_address',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Dirección del Cliente'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='client_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email del Cliente'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='client_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre del Cliente'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='client_phone',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Teléfono del Cliente'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='preferred_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha Preferida'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='preferred_time',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Hora Preferida'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='accounts.user'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Notas'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='services.service'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='staff_availability',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appointments.staffavailability'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('confirmed', 'Confirmada'), ('completed', 'Completada'), ('cancelled', 'Cancelada')], default='pending', max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='staffavailability',
            name='date',
            field=models.DateField(verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='staffavailability',
            name='end_time',
            field=models.TimeField(verbose_name='Hora de fin'),
        ),
        migrations.AlterField(
            model_name='staffavailability',
            name='is_available',
            field=models.BooleanField(default=True, verbose_name='Disponible'),
        ),
        migrations.AlterField(
            model_name='staffavailability',
            name='staff',
            field=models.ForeignKey(limit_choices_to={'is_staff': True}, on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='accounts.user'),
        ),
        migrations.AlterField(
            model_name='staffavailability',
            name='start_time',
            field=models.TimeField(verbose_name='Hora de inicio'),
        ),
    ]
