# Generated by Django 5.0.4 on 2025-04-07 22:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('appointments', '0007_alter_appointment_options_and_more'),
        ('services', '0002_service_slug_alter_serviceimage_image_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'verbose_name': 'Appointment', 'verbose_name_plural': 'Appointments'},
        ),
        migrations.AlterModelOptions(
            name='staffavailability',
            options={'verbose_name': 'Staff Availability', 'verbose_name_plural': 'Staff Availabilities'},
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='client_address',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='client_email',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='client_name',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='client_phone',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='preferred_date',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='preferred_time',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='accounts.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='appointment',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='service',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='services.service'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='appointment',
            name='staff_availability',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='appointments.staffavailability'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='staffavailability',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='staffavailability',
            name='end_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='staffavailability',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='staffavailability',
            name='staff',
            field=models.ForeignKey(limit_choices_to={'is_staff': True}, on_delete=django.db.models.deletion.CASCADE, to='accounts.user'),
        ),
        migrations.AlterField(
            model_name='staffavailability',
            name='start_time',
            field=models.TimeField(),
        ),
    ]
