# Generated by Django 5.0.4 on 2025-04-11 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0008_alter_appointment_options_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='appointment',
            table='cita',
        ),
        migrations.AlterModelTable(
            name='staffavailability',
            table='disponibilidad_personal',
        ),
    ]
