# Generated by Django 5.0.4 on 2025-04-30 14:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0009_alter_appointment_table_and_more'),
        ('services', '0003_alter_product_table_alter_service_table_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledWorkDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True, verbose_name='Fecha')),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='Hora de inicio general')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='Hora de fin general')),
                ('is_working', models.BooleanField(default=True, verbose_name='¿Se trabaja este día?')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notas generales del día')),
            ],
            options={
                'verbose_name': 'Día de Trabajo Programado',
                'verbose_name_plural': 'Días de Trabajo Programados',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='WorkScheduleTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')], unique=True, verbose_name='Día de la semana')),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='Hora de inicio')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='Hora de fin')),
                ('is_working_day', models.BooleanField(default=True, verbose_name='¿Es día laborable?')),
            ],
            options={
                'verbose_name': 'Plantilla de Horario Semanal',
                'verbose_name_plural': 'Plantillas de Horario Semanal',
                'ordering': ['day_of_week'],
            },
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='staff_availability',
        ),
        migrations.AlterModelOptions(
            name='appointment',
            options={'ordering': ['-appointment_date', '-appointment_time'], 'verbose_name': 'Cita', 'verbose_name_plural': 'Citas'},
        ),
        migrations.AddField(
            model_name='appointment',
            name='appointment_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de la Cita'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='appointment_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora de la Cita'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='staff',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_appointments', to=settings.AUTH_USER_MODEL, verbose_name='Personal Asignado'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_appointments', to=settings.AUTH_USER_MODEL, verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Notas del Cliente'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='services.service', verbose_name='Servicio'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('confirmed', 'Confirmada'), ('completed', 'Completada'), ('cancelled', 'Cancelada')], default='pending', max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterModelTable(
            name='appointment',
            table='citas',
        ),
        migrations.DeleteModel(
            name='StaffAvailability',
        ),
    ]
