# Generated by Django 5.0.4 on 2025-04-14 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0003_alter_quotation_options_alter_quotationitem_options_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='quotation',
            table='cotizacion',
        ),
        migrations.AlterModelTable(
            name='quotationitem',
            table='item_cotizacion',
        ),
    ]
