# Generated by Django 5.0.4 on 2025-04-07 22:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('appointments', '0008_alter_appointment_options_and_more'),
        ('quotations', '0004_alter_quotation_options_alter_quotationitem_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quotation',
            options={'verbose_name': 'Quotation', 'verbose_name_plural': 'Quotations'},
        ),
        migrations.AlterModelOptions(
            name='quotationitem',
            options={'verbose_name': 'Quotation Item', 'verbose_name_plural': 'Quotation Items'},
        ),
        migrations.AlterField(
            model_name='quotation',
            name='appointment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appointments.appointment'),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='quotation_number',
            field=models.CharField(max_length=20, unique=True, verbose_name='Quotation Number'),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='staff',
            field=models.ForeignKey(limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_quotations', to='accounts.user'),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='draft', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total Amount'),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='valid_until',
            field=models.DateField(default=1, verbose_name='Valid Until'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='quotationitem',
            name='description',
            field=models.CharField(max_length=200, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='quotationitem',
            name='item_type',
            field=models.CharField(choices=[('service', 'Service'), ('product', 'Product')], max_length=10, verbose_name='Item Type'),
        ),
        migrations.AlterField(
            model_name='quotationitem',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='quotationitem',
            name='total_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total Price'),
        ),
        migrations.AlterField(
            model_name='quotationitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Unit Price'),
        ),
    ]
