# Generated by Django 5.0.4 on 2025-04-08 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0005_alter_quotation_options_alter_quotationitem_options_and_more'),
    ]

    operations = [
    ]
