# Generated by Django 5.0.4 on 2025-04-11 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0006_auto_20250408_0821'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='quotation',
            table='cotizacion',
        ),
        migrations.AlterModelTable(
            name='quotationitem',
            table='item_cotizacion',
        ),
    ]
